eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhostt8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/schools/**
management:
  tracing:
    sampling:
      probability: 1.0
