server:
  port: 8090
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1122
    url: jdbc:postgresql://localhost:5432/students
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
